"""empty message

Revision ID: 08e39a7c0528
Revises: a1bf072bc149
Create Date: 2021-09-16 20:24:21.374614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e39a7c0528'
down_revision = 'a1bf072bc149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_ibfk_1', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'blog', ['bid'], ['bid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_ibfk_1', 'like', 'blog', ['bid'], ['uid'])
    # ### end Alembic commands ###
